### ISSUE TITLE
Bug: ruby_llm-monitoring assumes gc_time exists on ActiveSupport::Notifications::Event (Rails 7.1+)

### ISSUE THREAD

**Issue by Ukaypromise** [sinaptia/ruby_llm-monitoring#13]
### Summary

`ruby_llm-monitoring` v0.1.0 calls `event.gc_time` on `ActiveSupport::Notifications::Event`, but this method doesn't exist in Rails 7.1+. This causes `NoMethodError` crashes during LLM instrumentation.

#### Environment

- **Gem version**: `ruby_llm-monitoring` v0.1.0
- **Rails version**: 7.1.5.2
- **Ruby version**: 3.2.0
- **ActiveSupport version**: 7.1.5.2

#### Problem

The gem's `EventSubscriber` tries to access `event.gc_time`, but `ActiveSupport::Notifications::Event` doesn't expose this method:

```ruby
# In Rails console
ActiveSupport::Notifications::Event.public_instance_methods(false).sort
# => [:allocations, :children, :cpu_time, :duration, :end, :finish!, :idle_time, :name, :parent_of?, :payload, :payload=, :record, :start!, :time, :transaction_id]

ActiveSupport::Notifications::Event.method_defined?(:gc_time)
# => false
```

#### Error Stack Trace

```
NoMethodError: undefined method `gc_time' for #<ActiveSupport::Notifications::Event:0x...>
/Users/.../gems/ruby_llm-monitoring-0.1.0/lib/ruby_llm/monitoring/event_subscriber.rb:10:in `call'
/Users/.../gems/activesupport-7.1.5.2/lib/active_support/notifications/fanout.rb:181:in `block in finish'
```

#### Expected Behavior

The gem should work with Rails 7.1+ without crashing, either by:

1. Not calling `gc_time` if it doesn't exist
2. Using an alternative method (e.g., `cpu_time` which does exist)
3. Handling the missing method gracefully

#### Current Workaround

I implemented a monkey patch to prevent crashes:

```ruby
# config/initializers/ruby_llm_monitoring_fix.rb
module RubyLLM
  module Monitoring
    class EventSubscriber
      class EventWrapper
        def initialize(name, started, finished, unique_id, data)
          @event = ActiveSupport::Notifications::Event.new(name, started, finished, unique_id, data)
        end

        def method_missing(method_name, *args, &block)
          if method_name == :gc_time
            0  # Return 0 as fallback
          else
            @event.send(method_name, *args, &block)
          end
        end

        def respond_to_missing?(method_name, include_private = false)
          method_name == :gc_time || @event.respond_to?(method_name, include_private)
        end
      end

      alias_method :original_call, :call

      def call(name, started, finished, unique_id, data)
        begin
          wrapped_event = EventWrapper.new(name, started, finished, unique_id, data)
          original_call(wrapped_event)
        rescue StandardError => e
          Rails.logger.warn "[RubyLLM::Monitoring] Event subscriber error: #{e.message}"
        end
      end
    end
  end
end
```

#### Additional Context

- The `cpu_time` method exists and might be a suitable alternative
- This appears to be a compatibility issue with Rails 7.1+ (I do not get this issue with Rails 8+)
- The gem works fine otherwise, just needs to handle the missing method

## Suggested Fix

Check if `gc_time` exists before calling it, or use `cpu_time` as an alternative:

**Comment by patriciomacadden** [comment]
Hi @Ukaypromise, thanks for reporting the issue. And you're correct, the gc_time method was added in Rails 7.2 so it doesn't work with Rails 7.0.x and 7.1.x. 

I'm currently working on setting up the ci to test different versions of rails, so hopefully will get a solution soon.

**Comment by patriciomacadden** [comment]
Hi @Ukaypromise, again, thanks for reporting the issue. In #14 I updated the CI so it tests different ruby and rails versions combinations. I decided not to support EOL versions of Ruby and Rails. 

Ruby versions supported: https://www.ruby-lang.org/en/downloads/branches/
Rails versions supported: https://rubyonrails.org/maintenance

I don't want to ask you to upgrade your app to a newer versions of Rails, but if you do, everything shoud work as expected. In the meantime, your workaround should suffice.

I'm sorry for the inconvenience!

**Comment by Ukaypromise** [comment]
Thank you @patriciomacadden
